
title: "Dutch Post-CHI 2022"
logo: "./assets/imgs/chi2022.png"
description: "Dutch Post-CHI Event 2022"

# minimal_mistakes_skin: "contrast"
search: false

author:
  name     : "CHI NL"
  avatar   : "./assets/imgs/chi_nl_logo.png"
  bio      : "Something"
  location : "Somewhere"

footer:

kramdown:
  auto_ids: false

plugins:
  - jekyll-include-cache

remote_theme: mmistakes/minimal-mistakes

atom_feed: false

# defaults:
#   # _pages
#   - scope:
#       path: ""
#       type: pages
#     values:
#       layout: single
#       author_profile: false
